### ISSUE TITLE
is_valid_grammar() returns wrong answer on some grammars (ones with recursive expansions)

### ISSUE THREAD

**Issue by abhilashgupta** [uds-se/fuzzingbook#104]
**Describe the bug**
The function is_valid_grammar() in the Grammars chapter returns wrong answers (True on an invalid grammar)

**To Reproduce**

Consider the following invalid grammar in the eBNF form -
```
>>>pprint(fpg)
{
    "<start>": [
        "<a>"
    ],
    "<a>": [
        "<f>+"
    ]
}
```
Converting this to a regular BNF grammar using the convert_ebnf_grammar() function leads to the following representation -

```
>>> efpg = convert_ebnf_grammar(fpg)
>>> pprint(efpg)
{
    "<start>": [
        "<a>"
    ],
    "<a>": [
        "<f>"
    ],
    "<f>": [
        "<f>",
        "<f><f>"
    ]
}
```

Confirming the validity of this grammar with the is_valid_grammar() function returns True, when the grammar is clearly invalid -
```
>>> is_valid_grammar(efpg)
True
```

**Expected behavior**
I would expect is_valid_grammar() to return False on the above grammar.

**Desktop (please complete the following information):**
 - OS: macOS
 - Python version: Python 3.8.10

**Additional context**
I think the problem is that the nonterminal symbol `<f>` is reachable, has an expansion (albeit is never-ending) and is being used (albeit by itself) is what causes the is_valid_grammar() logic to fail.

**Comment by andreas-zeller** [comment]
Hi Abilash! As the chapter states, `is_valid_grammar()` only applies _static_ checks; it checks whether all used symbols are defined, and vice versa; it also checks whether all symbols are reachable from the start symbol. It does _not_ check whether producing from the grammar terminates (which seems to be the issue with `epfg`). Detecting that a grammar _always_ is non-terminating is beyond the capabilities of `is_valid_grammar()` at this point.

The problem is more that `fpg` is invalid in the first place, and `convert_ebnf_grammar()` creates a non-terminating grammar out of this. I will add an appropriate check into `convert_ebnf_grammar()` such that this is detected in time.
