### ISSUE TITLE
Binder Error loading

### ISSUE THREAD

**Issue by finco123** [uds-se/fuzzingbook#178]
**Describe the bug**
Notebooks launching by binder did not work as usual these days. About 1 month ago it worked normally.

**To Reproduce**
Go to [Try interacting with the introduction to fuzzing](https://mybinder.org/v2/gh/uds-se/fuzzingbook/master?filepath=docs/notebooks/Fuzzer.ipynb).

**Expected behavior**
Provide an environment to edit the notebooks interactively.

**Screenshots**
![image](https://github.com/uds-se/fuzzingbook/assets/44793329/8fe68f29-c2fb-4da9-81b5-d5c73bb79a53)

**Desktop (please complete the following information):**
Chrome

**Additional context**
Is there any changes for notebooks running?

**Comment by andreas-zeller** [comment]
This appears to be a mybinder.org problem. I have opened a request at

https://discourse.jupyter.org/t/build-fails-at-using-condabuildpack-builder/25742

**Comment by andreas-zeller** [comment]
This was due to the standard `repo2docker` tool running into a timeout on `mybinder`.
I have now created a custom `Dockerfile` that speeds up the recreation of `mybinder` virtual machines drastically, and thus avoids the timeout.  The `mybinder` service is now up and running again (with a few possible quirks).

**Comment by andreas-zeller** [comment]
The Dockerfile appears to resolbve the issue for now, so I am closing this bug.
